CREATE TABLE "GCG_6211_Mach_Export"(
 "MACHINE" CHAR(4),
 "Q_PATH" CHAR(100),
 "M_PATH" CHAR(100),
 "L_SEQ" INTEGER,
 "BATCH_SIZE" INTEGER,
 "R_PERIOD" INTEGER);

CREATE INDEX "GCG_6211_Mach_Export" ON "GCG_6211_Mach_Export" ( "MACHINE");


